'use strict';

const path = require( 'path' );
const enveloper = require( path.join( __dirname, 'index.js' ) );

module.exports = {
    command: 'encrypt <secret> [key] [--json]',
    builder: {
        json: {
            desc: 'outputs the result in json',
            default: false
        }
    },
    describe: 'Encrypt the given secret. If no key is specified, a key will be generated.',
    handler: options => {
        const input = {};

        if ( typeof options.key !== 'undefined' ) {
            input.key = options.key;
        }

        if ( typeof options.secret === 'undefined' ) {
            throw new Error( 'No secret specified!' );
        }

        // cast to a string to ensure things like numbers are treated properly
        const result = enveloper.seal( String( options.secret ), input );

        if ( options.json ) {
            console.log( JSON.stringify( result, null, 4 ) );
        }
        else {
            const string_result = enveloper.to_string( result );

            console.log( string_result );

            if ( typeof options.key === 'undefined' ) {
                console.log( `autogenerated key: ${ result.key }` );
            }
        }

    }
};
