'use strict';

const enveloper = require( '../index.js' );
const pkg = require( '../package.json' );

module.exports = {
    command: 'encrypt <secret> [key] [--json]',
    builder: {
        json: {
            desc: 'outputs the result in json',
            default: false
        }
    },
    describe: 'Encrypt the given secret. If no key is specified, a key will be generated.',
    handler: options => {
        const input = {};

        if ( typeof options.key !== 'undefined' ) {
            input.key = options.key;
        }

        const result = enveloper.seal( options.secret, input );

        if ( options.json ) {
            console.log( JSON.stringify( result, null, 4 ) );
        }
        else {
            const string_result = enveloper.to_string( result );

            console.log( string_result );

            if ( typeof options.key === 'undefined' ) {
                console.log( `autogenerated key: ${ result.key }` );
            }
        }

    }
};
