'use strict';

const enveloper = require( '../index.js' );
const program = require( 'commander' );
const pkg = require( '../package.json' );

program
    .version( pkg.version )
    .option( '--key <key>', 'specify the key to use, if no key is specified a new one will be generated' )
    .option( '--json', 'output the result as json' )
    .arguments( '<secret>')
    .action( ( secret ) => {
        const options = {};
        if ( typeof program.key !== 'undefined' ) {
            options.key = program.key;
        }

        const result = enveloper.seal( secret, options );

        if ( program.json ) {
            console.log( JSON.stringify( result, null, 4 ) );
        }
        else {
            const string_result = enveloper.to_string( result );

            console.log( string_result );

            if ( typeof program.key === 'undefined' ) {
                console.log( `autogenerated key: ${ result.key }` );
            }
        }
    } )
    .parse( process.argv );
